// GENERATED BY gg_version WriteVersionFile - DO NOT EDIT.
// Kept in sync by test/dna_readme_version.test.ts.

/** The version of the `@ggdna/dna-readme` package. */
export const dnaReadmeVersion = '0.1.1';
